version: '3.8'

services:
  mystore-admin-bot:
    build: .
    container_name: mystore-admin-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
